name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EC2_PRIVATE_KEY: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAgEAlZTUASlwHuizPszaMMEqKlBFgq9aAybQUf/WcyVR+uld24ehx7Et
        45U0zGSM8ao0+VYo+1/pfE5jtnVp5M0T9QzPjy6EZ4x1hR3nXm4callLgDOOS/1j4iBnle
        hW6/Q7V9d+MdiWG/QpNcDVP8yIsEtdAjFnjzNGwQaf7ZDvDP/Ylrhk6aVUlezb0nCOfWpk
        H8Qz6ge5lDaPkgzvP4Zs8WotuoJU1B8ftMBZSj/5Z+kqWAbhxmwZeI6lJDHT0SExD/TFqo
        idKbkdD9HgCHMZZrm8xxeYQHGE5x0Q/ayxSO5ebIOzzB2zH0e1+HHUtl4g+2shmNPZoBr/
        tM8UID1e41rnpN0JQaLKLnkKAr2Gzo7mKGW44KrLGLgXm4iA+0BooFrU2kmi7/W6QSRdqM
        aH3hm+r3tC28F4xJj4q34LrWvN9E6zApuGF2Be8bOoxTrzx5ZJSM/riKu830xcJy1hdx5p
        NKHjTwv12XJpVtuOIZtvP/cepCwwuDsfROZaW1vCrvLUd5Y9FfGyzUfGTyfBaJWXkVeeCL
        qVygoMTleCaSykg+Yr8bNjMGx2PwCEbR3WORR1BRj/C+E9NI2bbczk+GqRdwoIL8ATFtfU
        kgG8Vw5MSCkq2Q3CLwxRB0oHrQN6Z8pea6Op7FWkQNGCfeQmWerLT08rOqpZoC02eKEEZS
        EAAAdQKqSq8iqkqvIAAAAHc3NoLXJzYQAAAgEAlZTUASlwHuizPszaMMEqKlBFgq9aAybQ
        Uf/WcyVR+uld24ehx7Et45U0zGSM8ao0+VYo+1/pfE5jtnVp5M0T9QzPjy6EZ4x1hR3nXm
        4callLgDOOS/1j4iBnlehW6/Q7V9d+MdiWG/QpNcDVP8yIsEtdAjFnjzNGwQaf7ZDvDP/Y
        lrhk6aVUlezb0nCOfWpkH8Qz6ge5lDaPkgzvP4Zs8WotuoJU1B8ftMBZSj/5Z+kqWAbhxm
        wZeI6lJDHT0SExD/TFqoidKbkdD9HgCHMZZrm8xxeYQHGE5x0Q/ayxSO5ebIOzzB2zH0e1
        +HHUtl4g+2shmNPZoBr/tM8UID1e41rnpN0JQaLKLnkKAr2Gzo7mKGW44KrLGLgXm4iA+0
        BooFrU2kmi7/W6QSRdqMaH3hm+r3tC28F4xJj4q34LrWvN9E6zApuGF2Be8bOoxTrzx5ZJ
        SM/riKu830xcJy1hdx5pNKHjTwv12XJpVtuOIZtvP/cepCwwuDsfROZaW1vCrvLUd5Y9Ff
        GyzUfGTyfBaJWXkVeeCLqVygoMTleCaSykg+Yr8bNjMGx2PwCEbR3WORR1BRj/C+E9NI2b
        bczk+GqRdwoIL8ATFtfUkgG8Vw5MSCkq2Q3CLwxRB0oHrQN6Z8pea6Op7FWkQNGCfeQmWe
        rLT08rOqpZoC02eKEEZSEAAAADAQABAAACAAMTWV5OpvSSmXMAQldKrCYJoK7tBWrIUKq1
        0ND/YREAh8QVyZBbL/zuz8l82bELtXR3kMYO+Y/ZCt8PW4ydF3CgEJ4AlNp1ue5lJTOtqm
        VuKSspjuHXA9nj2saJ05XN2ZWQ47DMZsj54XfNABV+T2kvzKaiCQo4Qa/j4SvZOc+OtdKZ
        oPW+CiMapzAnFprBLDcwtauaHUAohwl6yUWDHBKIAvCAnDKraGWtCRauOLtCU2bxeXjbc8
        WrGS6MSmX/RJ7jp4ifiz4CwmIesrVqh61d5yscnY/BFQWhODnV6iEtGJbJRbO1w6t5RGBM
        C3QZcIP65GjoIjjrTA26cZ5Bm6Q1z2STFE4X+1zKKEu1MKY5EMsZ23ScZff2mSvYiTzo18
        7BjcbtMRWEI1gSb/UXDsuV1FHpTiTZIFkUH0y/KtUxBQGH41es65ywsB7XO485m+dS2Ia2
        Q7iIpfv8pCNL88E4O9R947kFxIqDK+bX03BTUatn5NsZT7sU3PeuLQY5J90dzMNBFvDphN
        nr5l0JSmVYljf0zs0wfLbm2NUv3NfOpenBVsHwG9z1m1DamfU1yoKs9fieqywzSR/20JWi
        9BkA1L5IP5d6Yxmk15mbf/AbnpOHx7vU7p+JEZ4JIlBSG6pjErSzZMs43NfcSaF0/kJO7r
        GIrX4PdCwdSl+WAb6pAAABAAnIPeCa71P1cf5DtcspIYdW3/CpHj2GDyIyPmeloE0686GM
        bD6mNNuwqtSCaO6htd01mY8FIBHp2FmLoZ4yxF7pws8ostKekOK+H3drA/tKJvc5WNJ4EX
        3ihs2q9RPgv3FXoBTg0vQectZ1hlFwgjTkvGnXDdX87BmhbBPcAxDTzXmzmjYQXk1LH420
        n9EthC+kka2NRkQ1yU0w/3xU1LD9kQ16xjcNYDwBnwQUlwF1/Rya56hQ+F7ycVt+QDlbwS
        kkblMXUPtTkG9aQep1plCmCZff3hEJxOr46EBPrtf5ZVsocPiV3WOekEO7PxJF9inbP1Ry
        SNnl6gRPDVvhwFgAAAEBAMv1ED+ZcjIEpXD/abBhFp7SgbRuyJp2eOwsaYQlD4VzZ+5daG
        b5j+NF4cGokmU+vPD/FVPWZYKwrPJJQFoxZW1Xl2ROoPAur5E7k8wY3t6heDRcsZ0T3G7U
        8k1FWe9rTrdtzz4FZQnJEpONg/EdU0Ycg4tw0AEBkbNJOABaT4pr43/AUC8bQRL4m25JVa
        EaomTKlcEbUExsk++BdfvDY47Eyi32R3qjaaPhYE9uajH50hMSBa50Ya890bLVDd+KBp0u
        TXDj4NQj8H9o3ze2bieBf2JCHzDeYEDYIDFxjXgGXFfYfNU3d8H8vQ09n9zP86QLcjDLEK
        TRi6618G4vLzsAAAEBALu/z3kHcXuIJLSkk/4UjRMzlxAnl4WJVU7TAsuTbWgZiYMJOHkD
        ge1q1XLgh0T0mlGjjYF2eXWvKEMCsvQYILlF11OsT/XgNZ2yylCgGMNmoehig+yFy1xA4K
        7N3KiMLkRCx8w5POZJKoKF5ZE5W5+dV1OepBTcycflCWypCGHL3Ci9JIk3/suAyGw97FRV
        bt4I7kaA5L+5ns01WTr97BNMHgZ94qupDC5W4r4DW2PoZmHTtQ71FiR3KRza/M9oRPHgB2
        mr134kxaFfBShIyMMAI8EGHFNws2fwoeRI/LUpHg0xY+wuACPmDVAnQtoRbzkm8Tsl1htT
        ZwdR/iXg71MAAAAWam9zdS5yaXZlcmFoQGdtYWlsLmNvbQECAwQF
        -----END OPENSSH PRIVATE KEY-----

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy Project to EC2
        uses: appleboy/scp-action@master
        with:
          host: 18.212.251.224
          username: root
          key: ${{ env.EC2_PRIVATE_KEY }}
          source: "./"
          target: "/"

      - name: SSH into EC2 and Run Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: 18.212.251.224
          username: root
          key: ${{ env.EC2_PRIVATE_KEY }}
          script: |
            cd ../scripts/
            bash docker_process.sh